openapi: 3.0.0
info:
  title: PRISA Tools
  description:
  version: 1.0.0
paths:
  /v1/data/:
    get:
      tags:
        - Data
      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
